apiVersion: apps/v1
kind: Deployment
metadata:
  name: ws-airsignal-deployment
  labels:
    app: ws-airsignal
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ws-airsignal
  template:
    metadata:
      labels:
        app: ws-airsignal
    spec:
      containers:
        - name: ws-airsignal
          image: 10nutz/ws-airsignal:latest
          ports:
            - containerPort: 12776
          env:
            - name: NODE_ENV
              value: "production"
