apiVersion: v1
kind: Service
metadata:
  name: ws-airsignal-service
spec:
  selector:
    app: ws-airsignal
  ports:
    - protocol: TCP
      port: 12776      
      targetPort: 12776
  type: LoadBalancer
