apiVersion: apps/v1
kind: Deployment
metadata:
  name: nakama
  namespace: nakama-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nakama
  template:
    metadata:
      labels:
        app: nakama
    spec:
      containers:
      - name: nakama
        image: registry.heroiclabs.com/heroiclabs/nakama:3.22.0
        env:
          - name: NAKAMA_DATABASE_ADDRESS
            value: "postgres:localdb@postgres:5432/nakama"
          - name: NAKAMA_DATABASE_PASSWORD
            value: "localdb"
        command: ["/bin/sh", "-ecx"]
        args:
          - >
            /nakama/nakama migrate up --database.address postgres:localdb@postgres:5432/nakama &&
            exec /nakama/nakama --name nakama1
            --database.address postgres:localdb@postgres:5432/nakama
            --logger.level DEBUG
            --session.token_expiry_sec 7200
        ports:
          - name: grpc
            containerPort: 7349
          - name: http
            containerPort: 7350
          - name: console
            containerPort: 7351
        volumeMounts:
          - name: nakama-data
            mountPath: /nakama/data
      volumes:
        - name: nakama-data
          persistentVolumeClaim:
            claimName: nakama-pvc
