apiVersion: v1
kind: Service
metadata:
  name: nakama
  namespace: nakama-namespace
spec:
  type: LoadBalancer
  ports:
    - name: grpc
      port: 7349
      targetPort: 7349
    - name: http
      port: 7350
      targetPort: 7350
    - name: console 
      port: 7351
      targetPort: 7351
  selector:
    app: nakama
