apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: nakama-namespace
spec:
  serviceName: "postgres"
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:12.2-alpine
        ports:
          - containerPort: 5432
        env:
          - name: POSTGRES_DB
            value: "nakama"
          - name: POSTGRES_PASSWORD
            value: "localdb"
        volumeMounts:
          - name: postgres-storage
            mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
